config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'static_pages#index'

  resources :users, only: %i[index show edit update] do
    member do
      delete 'destroy_attached_avatar', to: 'users#destroy_attached_avatar', as: 'destroy_avatar_attached_to'
    end
    resources :friendships, only: %i[index destroy]

    get 'friends', to: 'friendships#index'
    delete 'remove_friend/:id', to: 'friendships#destroy', as: 'remove_friend'
  end

  resources :posts, except: %i[new show] do
    resources :comments, only: %i[create destroy edit update]
    post 'like', to: 'likes#create'
    delete 'like', to: 'likes#destroy'
  end

  post 'friends', to: 'friendships#create'
  delete 'friend_request/:requester_id/:requestee_id', to: 'friend_requests#destroy', as: 'friend_request'
  get 'sent_requests', to: 'friend_requests#sent_requests'
  post 'add_friend', to: 'friend_requests#create'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: %i[create]
  before_action :find_comment, only: %i[destroy edit update]
  before_action :find_user, only: %i[destroy edit update]
  before_action :authorize_current_user, only: %i[destroy edit update]

  def create
    @comment = current_user.comment(@post, comment_params[:content])

    if @comment
      redirect_back fallback_location: posts_path, notice: 'Comment posted!'
    else
      redirect_back fallback_location: posts_path, alert: 'Comment failed'
    end
  end

  def destroy
    if @comment.destroy
      redirect_back fallback_location: posts_path, notice: 'Comment deleted!'
    else
      redirect_back fallback_location: posts_path, alert: 'Failed to delete comment.'
    end
  end

  def edit
    session[:edit_redirect] = request.referrer
  end

  def update
    if @comment.update(comment_params)
      edit_redirect = session[:edit_redirect] || posts_path
      session[:edit_redirect] = nil
      redirect_to edit_redirect, notice: 'You have edited your comment'
    else
      render 'edit'
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = Comment.includes(:user).find(params[:id])
  end

  def find_user
    @user = @comment.user
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card my-2 offset-1" id="comment-<%= comment.id %>">
  <div class="card-body d-flex justify-content-between align-items-center">
    <%= comment.content %>
    <h6 class="card-subtitle text-muted d-flex align-items-center">
      <span>
        <% if comment.user == current_user %>
          <%= link_to 'Edit', edit_post_comment_path(comment.post, comment), class: 'card-link' %>
          <%= link_to 'Delete', post_comment_path(comment.post, comment), method: :delete, class: 'card-link text-danger mr-3', data: { confirm: 'Are you sure?' } %>
        <% end %>
      </span>
      <span>
        <%= time_ago_in_words(comment.created_at) %> ago by
        <%= link_to comment.user, class: 'text-decoration-none text-reset' do %>
          <%= comment.user.name %>
          <%= avatar_tag comment.user, size: 30, class: 'round-avatar' %>
        <% end %>
      </span>
    </h6>
  </div>
</div>

app/views/comments/edit.html.erb
<%= form_with(model: [@comment.post, @comment], local: true, class: 'text-center card p-3 mb-3', id: "comment-#{@comment.id}") do |f| %>
  <div class="form-group card-body p-1">
    <%= f.label :content, 'Comment' %>
    <%= render 'devise/shared/error_messages', resource: @comment %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <%= f.submit 'Edit comment', class: 'btn btn-primary' %>
<% end %>