config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'static_pages#index'

  resources :users, only: %i[index show edit update] do
    member do
      delete 'destroy_attached_avatar', to: 'users#destroy_attached_avatar', as: 'destroy_avatar_attached_to'
    end
    resources :friendships, only: %i[index destroy]

    get 'friends', to: 'friendships#index'
    delete 'remove_friend/:id', to: 'friendships#destroy', as: 'remove_friend'
  end

  resources :posts, except: %i[new show] do
    resources :comments, only: %i[create destroy edit update]
    post 'like', to: 'likes#create'
    delete 'like', to: 'likes#destroy'
  end

  post 'friends', to: 'friendships#create'
  delete 'friend_request/:requester_id/:requestee_id', to: 'friend_requests#destroy', as: 'friend_request'
  get 'sent_requests', to: 'friend_requests#sent_requests'
  post 'add_friend', to: 'friend_requests#create'
end

app/models/user.rb
require 'open-uri'

class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 26 }
  validates :summary, length: { maximum: 200 }

  has_one_attached :avatar, dependent: :destroy
  has_many :friend_requests, class_name: 'FriendRequest',
                             foreign_key: 'requestee_id',
                             dependent: :destroy
  has_many :sent_requests, class_name: 'FriendRequest',
                           foreign_key: 'requester_id',
                           dependent: :destroy

  has_many :requestees, through: :sent_requests
  has_many :requesters, through: :friend_requests

  has_many :friendships, dependent: :destroy

  has_many :friends, class_name: 'User',
                     through: :friendships,
                     foreign_key: 'friend_id'

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  default_scope { order(:name) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: %i[discord]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      info = auth.info

      user.email = info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = info.name
      user.attach_avatar_from_url info.image if info.image.present?

      user.skip_confirmation!
    end
  end

  def attach_avatar_from_url(avatar_url)
    picture = OpenStruct.new(io: URI.open(avatar_url), ext: File.extname(avatar_url))
    file_base_tokens = name.scan(/\w+/)
    file_base_name = file_base_tokens.join('_')
    filename = file_base_name + picture.ext

    avatar.attach(io: picture.io, filename: filename)
  end

  def request_to_be_friends(user)
    sent_requests.create(requestee: user)
  end

  def friend_request_from(user)
    friend_requests.find_by(requester: user)
  end

  def friend_request_to(user)
    sent_requests.find_by(requestee: user)
  end

  def accept_friend_request_from(other_user)
    request = friend_request_from(other_user)
    return unless request

    Friendship.transaction do
      FriendRequest.transaction do
        request.destroy
        friendships.create(friend: other_user)
      end
    end
  end

  def cancel_request(requestee)
    friend_request_to(requestee)&.destroy
  end

  def requestable_friends
    User.where('id NOT IN (:friends)', friends: friends.select(:id))
        .where('id NOT IN (:requestees)', requestees: requestees.select(:id))
        .where('id NOT IN (:requesters)', requesters: requesters.select(:id))
        .where('id != ?', id)
  end

  def add_friend(friend)
    friendships.create(friend: friend)
  end

  def remove_friend(friend)
    friendship = friendships.find_by(friend: friend)
    friendship&.destroy
  end

  # returns the relationship of the other user to self
  def relationship(user)
    if self == user
      :self
    elsif sent_requests.find_by(requestee_id: user.id)
      :requestee
    elsif friend_requests.find_by(requester_id: user.id)
      :requester
    elsif friendships.find_by(friend_id: user.id)
      :friend
    end
  end

  def like(post)
    likes.create(post: post)
  end

  def unlike(post)
    likes.find_by(post: post)&.destroy
  end

  def post(content)
    posts.create(content: content)
  end

  def comment(post, content)
    comments.create(post: post, content: content)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :discord

  def discord
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Discord') if is_navigational_format?
    else
      session['devise.discord_data'] = request.env['omniauth.auth'].except(:extra) # extra can overflow some session stores
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, except: %i[index]
  before_action :authorize_current_user, except: %i[index show]

  def index
    @users = current_user.requestable_friends
                         .paginate(page: params[:page], per_page: 10)
                         .with_attached_avatar
  end

  def show
    @relationship = current_user.relationship(@user)
    @post = @user.posts.new
    @posts = Post.where(user: @user)
  end

  def edit; end

  def update
    if @user.update(profile_params)
      redirect_to @user, notice: 'Successfully updated!'
    else
      flash.now[:alert] = 'Update failed.'
      render 'edit'
    end
  end

  def destroy_attached_avatar
    @user.avatar.purge if @user.avatar.attached?
    redirect_back(fallback_location: user_path(@user))
  end

  private

  def profile_params
    params.require(:user).permit(:name, :summary, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_link(user, size)
    if user.avatar.attached?
      user.avatar.variant resize_to_fill: [size, size]
    else
      'odin-logo.svg'
    end
  end

  def avatar_tag(user, size: 200, **opts)
    image_tag avatar_link(user, size), width: size, height: size, **opts
  end

  def round_avatar_tag(user, size: 200, **opts)
    avatar_tag user, size: size, **opts
  end
end

app/views/users/_manage_relationship.html.erb
<% case @relationship %>
<% when :self %>
<% when :requestee %>
  <%= button_to friend_request_path(current_user, @user), params: { friend_id: @user.id }, method: :delete, class: "text-reset m-1 btn btn-danger" do %>
    <span class="text-white">
      Cancel request
    </span>
  <% end %>
<% when :requester %>
  <%= button_to friends_path, params: { friend_id: @user.id }, class: "text-reset m-1 btn btn-primary" do %>
    <span class="text-white">
      Add friend
    </span>
  <% end %>
<% when :friend %>
  <%= button_to user_remove_friend_path(current_user, @user), method: :delete, class: "text-reset m-1 btn btn-danger", data: { confirm: 'Are you sure?' } do %>
    <span class="text-white">
      Remove friend
    </span>
  <% end %>
<% else %>
  <%= button_to add_friend_path, params: { requestee_id: @user.id }, class: "text-reset m-1 btn btn-primary" do %>
    <span class="text-white">
      Send request
    </span>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>Update Your Profile</h2>
<hr />

<%= form_with model: @user, local: true do |f| %>
  <%= render 'devise/shared/error_messages', resource: @user %>
  <div class="form-group">
    <%= f.label :name, 'Display name' %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    Current avatar
    <%= avatar_tag @user, size: 100, class: 'd-block my-2' %> 
    <%= f.label :avatar, 'Upload a new avatar', class: 'mb-0' %>
    <%= f.file_field :avatar, class: 'form-control-file', accept: 'image/*', direct_upload: true %>
  </div>

  <%= f.submit 'Update profile', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<% provide :page, 'Find Friends' %>
<% provide :button_partial_path, 'friend_requests/add_friend' %>

<%= render "shared/user_list" %>

app/views/users/show.html.erb
<% provide :page, 'User Profile' %>

<div class="profile jumbotron text-center">
  <%= round_avatar_tag @user, class: 'round-avatar mb-3' %>

  <h1 class="display-4">
    <%= @user.name %>
  </h1>
  <hr >
    <p>
      <% if @user.summary.present? %>
        <%= @user.summary %>
      <% else %>
        An Odinbook member.
      <% end %>
    </p>
    <div class="d-flex justify-content-center">
      <%= link_to user_friends_path(@user), class: "text-reset m-1 btn btn-secondary" do %>
        <span class="text-white">
          <%= pluralize(@user.friends.count, 'friend') %>
        </span>
      <% end %>
      <%= render "manage_relationship" %>
    </div>
  <% if @user == current_user %>
    <div class="d-flex justify-content-center">
      <%= link_to edit_user_path(@user), class: "text-reset mx-1 btn btn-secondary" do %>
        <span class="text-white">
          <%= fa_icon "edit" %> profile
        </span>
      <% end %>
      <% if @user.avatar.attached? %>
        <%= link_to destroy_avatar_attached_to_user_path(@user), method: :delete, class: "text-reset mx-1 btn btn-danger" do %>
          <span class="text-white">
            <%= fa_icon "trash" %> avatar
          </span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<% provide :post_prompt, 'Share a post' %>
<% provide :post_button, 'Post' %>
<% if @user == current_user %>
  <%= render "posts/form" %>
<% end %>
<h3>
  Posts
</h3>
<%= render @posts %>