config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'static_pages#index'

  resources :users, only: %i[index show edit update] do
    member do
      delete 'destroy_attached_avatar', to: 'users#destroy_attached_avatar', as: 'destroy_avatar_attached_to'
    end
    resources :friendships, only: %i[index destroy]

    get 'friends', to: 'friendships#index'
    delete 'remove_friend/:id', to: 'friendships#destroy', as: 'remove_friend'
  end

  resources :posts, except: %i[new show] do
    resources :comments, only: %i[create destroy edit update]
    post 'like', to: 'likes#create'
    delete 'like', to: 'likes#destroy'
  end

  post 'friends', to: 'friendships#create'
  delete 'friend_request/:requester_id/:requestee_id', to: 'friend_requests#destroy', as: 'friend_request'
  get 'sent_requests', to: 'friend_requests#sent_requests'
  post 'add_friend', to: 'friend_requests#create'
end

app/views/shared/_comment_form.html.erb
<div class="dropdown">
  <button class="btn btn-secondary btn-sm" type="button" data-toggle="collapse" data-target="#post-<%= post.id %>-new-comment" aria-expanded="false" aria-controls="post-<%= post.id %>-new-comment">
    Comment
  </button>
</div>

app/views/shared/_like_button.html.erb
<% if post.likes.any? { |like| like.user == current_user } %>
  <%= button_to likes(post), post_like_path(post), method: :delete, class: 'btn btn-primary btn-sm mr-3'  %>
<% else %>
  <%= button_to likes(post), post_like_path(post), class: 'btn btn-outline-primary btn-sm mr-3'  %>
<% end %>

app/views/shared/_post_management.html.erb
<div class="float-right">
  <% if post.user == current_user %>
    <%= link_to 'Edit', edit_post_path(post), class: 'card-link ml-3' %>
    <%= link_to 'Delete', post_path(post), method: :delete, class: 'card-link text-danger mr-1', data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/shared/_user_list.html.erb
<% if @users.empty? %>
  <div class="text-center">
    <h1><%= yield(:page) %></h1>
    <p><%= yield(:empty_page_message) %></p>
  </div>
<% else %>
<div class="d-flex justify-content-center align-items-center justify-content-lg-between flex-wrap flex-lg-nowrap pb-2 pb-lg-0" >
  <h1 class="my-0 mx-2"><%= yield(:page) %></h1>
  <%= will_paginate @users %>
</div>
<div>
  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="d-flex justify-content-between align-items-center list-group-item">
        <%= link_to user, class: "text-reset text-decoration-none", id: user.id do %>
          <%= round_avatar_tag user, size: 40, class: 'round-avatar mr-2' %>
          <%= user.name %>
        <% end %>
        <% if local_assigns.fetch :show_button, true %>
            <%= render yield(:button_partial_path), user: user %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<% end %>