config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'static_pages#index'

  resources :users, only: %i[index show edit update] do
    member do
      delete 'destroy_attached_avatar', to: 'users#destroy_attached_avatar', as: 'destroy_avatar_attached_to'
    end
    resources :friendships, only: %i[index destroy]

    get 'friends', to: 'friendships#index'
    delete 'remove_friend/:id', to: 'friendships#destroy', as: 'remove_friend'
  end

  resources :posts, except: %i[new show] do
    resources :comments, only: %i[create destroy edit update]
    post 'like', to: 'likes#create'
    delete 'like', to: 'likes#destroy'
  end

  post 'friends', to: 'friendships#create'
  delete 'friend_request/:requester_id/:requestee_id', to: 'friend_requests#destroy', as: 'friend_request'
  get 'sent_requests', to: 'friend_requests#sent_requests'
  post 'add_friend', to: 'friend_requests#create'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to 'Odinbook', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <%= activatable_nav_li 'Home' do %>
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      <% end %>
      <%= activatable_nav_li 'Find Friends' do %>
        <%= link_to 'Find Friends', users_path, class: 'nav-link' %>
      <% end %>
      <% if user_signed_in? %>
        <%= activatable_nav_li 'Feed' do %>
          <%= link_to 'Feed', posts_path, class: 'nav-link' %>
        <% end %>
        <%= activatable_nav_li 'Sent Requests' do %>
          <%= link_to 'Sent Requests', sent_requests_path, class: 'nav-link' %>
        <% end %>
        <%= activatable_nav_li 'User Profile' do %>
          <%= link_to current_user.name, current_user, class: 'nav-link' %>
        <% end %>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <%= render "layouts/logged_in_nav" %>
      <% else %>
        <li class="nav-item"><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_logged_in_nav.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="profile-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= "Signed in as #{current_user.name}" %>
  </a>
  <div class="dropdown-menu" aria-labelledby="profile-dropdown">
    <%= link_to "View profile", user_path(current_user), class: 'dropdown-item' %>
    <%= link_to "Update profile", edit_user_path(current_user), class: 'dropdown-item' %>
    <%= link_to "Manage account", edit_user_registration_path , class: 'dropdown-item' %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
  </div>
</li>
<li class="nav-item dropdown">
  <% if @requesters.empty? %>
    <% notification_class = 'nav-link dropdown-toggle' %>
  <% else %>
    <% notification_class = 'nav-link dropdown-toggle text-warning' %>
  <% end %>
  <a class="<%= notification_class %>" href="#" id="notification-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= fa_icon 'bell' %>
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="notification-dropdown">
    <% if @requesters.empty? %>
      <h3 class='dropdown-header'>No notifications</h6>
    <% else %>
      <h6 class='dropdown-header text-center'>Friend requests</h6>
      <% @requesters.each do |requester| %>
        <div class="dropdown-item px-3", id="<%= requester.id %>">
          <%= link_to requester, class: 'd-flex align-items-center justify-content-between text-decoration-none text-dark' do %>
            <span class='mx-1'>
              <%= avatar_tag(requester, size: 50, class:'round-avatar mx-2') %>
              <%= requester.name %>
            </span>
            <span class="d-flex mx-0">
              <%= button_to 'Accept', friends_path, params: { friend_id: requester.id }, class: 'btn btn-primary mx-1' %>
              <%= button_to 'Reject', friend_request_path(requester, current_user), method: :delete, class: 'btn btn-danger mx-1' %>
            </span>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</li>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_flash(type) %>">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden"true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odinbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main role="main" class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </main>
  </body>
</html>